import {readFile, writeFile, mkdir} from 'node:fs/promises';
import {dirname} from 'node:path';
export const escapeHtml = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const site='https://www.expediaservices.ae';
export function renderPage(page,pages) {
 const e=escapeHtml;
 const guides=pages.filter(p=>p.path.startsWith('/blog/'));
 const links=pages.filter(p=>['/blog','/privacy','/cookies','/terms'].includes(p.path));
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(page.title)} | Expedia Business Services</title><meta name="description" content="${e(page.description)}"><link rel="canonical" href="${site}${e(page.path)}"><meta property="og:title" content="${e(page.title)}"><meta property="og:description" content="${e(page.description)}"><meta property="og:url" content="${site}${e(page.path)}"><meta property="og:type" content="${page.path.startsWith('/blog/')?'article':'website'}"><meta property="og:locale" content="en_AE"><meta property="og:image" content="${site}/expedia-latest-logo.png"><link rel="icon" href="/icon-logo.png"><style>
body{margin:0;background:#faf7f0;color:#28251f;font-family:system-ui,sans-serif;font-size:18px;line-height:1.75}header,main,footer{max-width:800px;margin:auto;padding:24px}header{border-bottom:1px solid #d8cfbe}nav{display:flex;flex-wrap:wrap;gap:12px 24px}a{color:#79581f;text-underline-offset:4px}a:focus-visible{outline:3px solid #087f5b;outline-offset:4px}h1{font-size:clamp(30px,5vw,46px);line-height:1.2}h2{font-size:25px;line-height:1.35;margin-top:36px}p,li{overflow-wrap:anywhere}.meta{font-size:15px;color:#575044}footer{border-top:1px solid #d8cfbe;margin-top:32px;padding-bottom:48px}.logo{width:210px;max-width:100%;height:auto}.skip{position:absolute;top:-100px}.skip:focus{top:10px;background:white;padding:12px}.contact{padding:20px;background:white;border:1px solid #d8cfbe;border-radius:12px}li{margin-bottom:12px}main:focus{outline:none}
</style></head><body><a class="skip" href="#main-content">Skip to content</a><header><a href="/" aria-label="Expedia home"><img class="logo" src="/expedia-latest-logo.png" alt="Expedia Business Services" width="1879" height="841"></a><nav aria-label="Main navigation"><a href="/">Home</a><a href="/#services">Services</a><a href="/blog">Guides</a><a href="/#contact">Contact</a></nav></header><main id="main-content" tabindex="-1"><article><h1>${e(page.title)}</h1><p class="meta">Reviewed 10 September 2026 · Expedia Business and Services L.L.C</p><p>${e(page.description)}</p>${page.sections.map(s=>`<section><h2>${e(s.heading)}</h2>${s.paragraphs.map(p=>`<p>${e(p)}</p>`).join('')}</section>`).join('')}${page.path==='/blog'?`<ul>${guides.map(g=>`<li><a href="${e(g.path)}">${e(g.title)}</a><p>${e(g.description)}</p></li>`).join('')}</ul>`:''}${page.sources.length?`<section><h2>Official sources</h2><ul>${page.sources.map(s=>`<li><a href="${e(s.url)}" rel="noopener noreferrer">${e(s.label)}</a></li>`).join('')}</ul></section>`:''}</article><section class="contact"><h2>Speak to our team</h2><p><a href="/#contact">Send an enquiry</a> or email <a href="mailto:info@expediaservices.ae">info@expediaservices.ae</a>.</p><p><a href="tel:+971564425950">+971 56 4425 950</a> · Haibu, Level 1, Abu Dhabi Mall, Abu Dhabi, UAE</p></section></main><footer><nav aria-label="Guides and policies">${links.map(p=>`<a href="${e(p.path)}">${e(p.title)}</a>`).join('')}</nav><p class="meta">Expedia Business and Services L.L.C</p></footer></body></html>`;
}
export async function writeRestoredPages(){
 const pages=JSON.parse(await readFile('content/restored-pages.json','utf8'));
 for(const page of pages){const file='dist'+page.path+'.html';await mkdir(dirname(file),{recursive:true});await writeFile(file,renderPage(page,pages));}
 return pages.map(p=>site+p.path);
}
